//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShineYatraAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShineYatraAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string AddressOne {
            get {
                return ResourceManager.GetString("AddressOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string AddressTwo {
            get {
                return ResourceManager.GetString("AddressTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adt.
        /// </summary>
        public static string AdultCode {
            get {
                return ResourceManager.GetString("AdultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Search.
        /// </summary>
        public static string AdvanceSearch {
            get {
                return ResourceManager.GetString("AdvanceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airlines Structure.
        /// </summary>
        public static string AirlinesStructure {
            get {
                return ResourceManager.GetString("AirlinesStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        public static string Api {
            get {
                return ResourceManager.GetString("Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Services.
        /// </summary>
        public static string BillServices {
            get {
                return ResourceManager.GetString("BillServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS Groups.
        /// </summary>
        public static string BUSGroups {
            get {
                return ResourceManager.GetString("BUSGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Structure.
        /// </summary>
        public static string BusStructure {
            get {
                return ResourceManager.GetString("BusStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cab Services.
        /// </summary>
        public static string Cab {
            get {
                return ResourceManager.GetString("Cab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chd.
        /// </summary>
        public static string ChildCode {
            get {
                return ResourceManager.GetString("ChildCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMISSION%.
        /// </summary>
        public static string Commissionpercent {
            get {
                return ResourceManager.GetString("Commissionpercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission Structure.
        /// </summary>
        public static string CommissionStructure {
            get {
                return ResourceManager.GetString("CommissionStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Web Site.
        /// </summary>
        public static string CompanyWebSite {
            get {
                return ResourceManager.GetString("CompanyWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No..
        /// </summary>
        public static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Search Parameters.
        /// </summary>
        public static string CustomSearchParameters {
            get {
                return ResourceManager.GetString("CustomSearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT SETTINGS.
        /// </summary>
        public static string DefaultSetting {
            get {
                return ResourceManager.GetString("DefaultSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic.
        /// </summary>
        public static string Domestic {
            get {
                return ResourceManager.GetString("Domestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTH.
        /// </summary>
        public static string Dth {
            get {
                return ResourceManager.GetString("Dth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Booking.
        /// </summary>
        public static string FlightBooking {
            get {
                return ResourceManager.GetString("FlightBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Groups.
        /// </summary>
        public static string FlightGroups {
            get {
                return ResourceManager.GetString("FlightGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Booking.
        /// </summary>
        public static string HotelBooking {
            get {
                return ResourceManager.GetString("HotelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Groups.
        /// </summary>
        public static string HotelGroups {
            get {
                return ResourceManager.GetString("HotelGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Structure.
        /// </summary>
        public static string HotelStructure {
            get {
                return ResourceManager.GetString("HotelStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrant.
        /// </summary>
        public static string Infant {
            get {
                return ResourceManager.GetString("Infant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inf.
        /// </summary>
        public static string InfantCode {
            get {
                return ResourceManager.GetString("InfantCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        public static string International {
            get {
                return ResourceManager.GetString("International", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string LoginAccount {
            get {
                return ResourceManager.GetString("LoginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Companies.
        /// </summary>
        public static string ManageCompanies {
            get {
                return ResourceManager.GetString("ManageCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Company.
        /// </summary>
        public static string ManageCompany {
            get {
                return ResourceManager.GetString("ManageCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Distributors.
        /// </summary>
        public static string ManageDistributors {
            get {
                return ResourceManager.GetString("ManageDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Groups.
        /// </summary>
        public static string ManageGroups {
            get {
                return ResourceManager.GetString("ManageGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage WL-&gt;User.
        /// </summary>
        public static string ManageWhiteLabelUser {
            get {
                return ResourceManager.GetString("ManageWhiteLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW Fund Request.
        /// </summary>
        public static string NewFundRequest {
            get {
                return ResourceManager.GetString("NewFundRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP.
        /// </summary>
        public static string Otp {
            get {
                return ResourceManager.GetString("Otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        public static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTPAID.
        /// </summary>
        public static string Postpaid {
            get {
                return ResourceManager.GetString("Postpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREPAID.
        /// </summary>
        public static string Prepaid {
            get {
                return ResourceManager.GetString("Prepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCH-DTH Groups.
        /// </summary>
        public static string RchDthGroups {
            get {
                return ResourceManager.GetString("RchDthGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCH-PostPaid Groups.
        /// </summary>
        public static string RCHPostPaidGroups {
            get {
                return ResourceManager.GetString("RCHPostPaidGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCH-PrePaid Groups.
        /// </summary>
        public static string RCHPrePaidGroups {
            get {
                return ResourceManager.GetString("RCHPrePaidGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge.
        /// </summary>
        public static string Recharge {
            get {
                return ResourceManager.GetString("Recharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge Structure.
        /// </summary>
        public static string RechargeStructure {
            get {
                return ResourceManager.GetString("RechargeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Parameters.
        /// </summary>
        public static string SearchParameters {
            get {
                return ResourceManager.GetString("SearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        public static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string Sms {
            get {
                return ResourceManager.GetString("Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility Portal DomainName.
        /// </summary>
        public static string UtilityPortalDomainName {
            get {
                return ResourceManager.GetString("UtilityPortalDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility Web Site.
        /// </summary>
        public static string UtilityWebSite {
            get {
                return ResourceManager.GetString("UtilityWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Credit Limit.
        /// </summary>
        public static string WalletCreditLimit {
            get {
                return ResourceManager.GetString("WalletCreditLimit", resourceCulture);
            }
        }
    }
}
